# Generated by Django 5.2.17 on 2026-08-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account_id', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('followers_count', models.BigIntegerField()),
                ('media_count', models.BigIntegerField()),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Snapshot do perfil',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramCollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('sucesso', 'Sucesso'), ('parcial', 'Concluída com erros'), ('erro', 'Falhou')], default='executando', max_length=12)),
                ('escopo', models.CharField(blank=True, max_length=200)),
                ('media_discovered', models.IntegerField(default=0)),
                ('media_updated', models.IntegerField(default=0)),
                ('snapshots_created', models.IntegerField(default=0)),
                ('requests_made', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução da coleta',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_media_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=20)),
                ('media_product_type', models.CharField(max_length=20)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('like_count', models.BigIntegerField(blank=True, null=True)),
                ('comments_count', models.BigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tema', models.CharField(blank=True, max_length=60)),
                ('subtema', models.CharField(blank=True, max_length=60)),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('resumo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publicação do Instagram',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramMediaMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('reach', models.BigIntegerField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('saved', models.BigIntegerField(blank=True, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('reposts', models.BigIntegerField(blank=True, null=True)),
                ('total_interactions', models.BigIntegerField(blank=True, null=True)),
                ('total_watch_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('avg_watch_time_ms', models.BigIntegerField(blank=True, null=True)),
                ('reels_skip_rate', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.instagrammedia')),
            ],
            options={
                'verbose_name': 'Snapshot de métricas',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['media', 'collected_at'], name='analytics_i_media_i_ec7e51_idx')],
            },
        ),
    ]
