# Generated by Django 5.2.17 on 2026-08-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('corpo_markdown', models.TextField(verbose_name='Conteúdo (Markdown)')),
                ('periodo_inicio', models.DateField(verbose_name='Início do período analisado')),
                ('periodo_fim', models.DateField(verbose_name='Fim do período analisado')),
                ('dados_coletados_em', models.DateTimeField(help_text='Momento do snapshot dos números usados na análise (vem no CSV exportado).', verbose_name='Dados coletados em')),
                ('publico', models.BooleanField(default=False, help_text='Se marcado, o relatório aparece em /relatorios/ para qualquer visitante.', verbose_name='Visível no site público')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Relatório de análise',
                'verbose_name_plural': 'Relatórios de análise',
                'ordering': ['-criado_em'],
            },
        ),
    ]
