# Generated by Django 5.2.17 on 2026-08-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_relatorioanalise'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccountDailyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Dia')),
                ('new_followers', models.IntegerField(blank=True, null=True, verbose_name='Novos seguidores')),
                ('reach', models.BigIntegerField(blank=True, null=True, verbose_name='Alcance do dia')),
                ('collected_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Métrica diária da conta',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_media_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('media_type', models.CharField(max_length=20)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='instagramcollectionrun',
            name='dias_atualizados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramcollectionrun',
            name='stories_snapshots',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InstagramStoryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('reach', models.BigIntegerField(blank=True, null=True)),
                ('replies', models.BigIntegerField(blank=True, null=True)),
                ('shares', models.BigIntegerField(blank=True, null=True)),
                ('total_interactions', models.BigIntegerField(blank=True, null=True)),
                ('navigation', models.BigIntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.instagramstory')),
            ],
            options={
                'verbose_name': 'Snapshot de story',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['story', 'collected_at'], name='analytics_i_story_i_ff427f_idx')],
            },
        ),
    ]
