# Generated by Django 5.2.17 on 2026-08-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_instagramaccountdailyinsight_instagramstory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioanalise',
            name='publico',
        ),
    ]
