# Generated by Django 5.2.17 on 2026-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('inicio', models.DateTimeField(verbose_name='Data e hora')),
                ('municipio', models.CharField(max_length=80, verbose_name='Município')),
                ('local', models.CharField(blank=True, max_length=160, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('responsavel', models.CharField(blank=True, max_length=80, verbose_name='Responsável na equipe')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=12, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Compromisso de agenda',
                'verbose_name_plural': 'Agenda interna',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='DemandaEscuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('educacao', 'Educação'), ('ciencia', 'Ciência e tecnologia'), ('qualificacao', 'Qualificação e emprego'), ('esporte', 'Esporte'), ('cultura', 'Cultura'), ('juventude', 'Juventude'), ('regional', 'Desenvolvimento regional')], max_length=20, verbose_name='Tema')),
                ('municipio', models.CharField(max_length=80, verbose_name='Município')),
                ('descricao', models.TextField(verbose_name='Descrição da demanda')),
                ('origem', models.CharField(choices=[('instagram', 'Instagram'), ('presencial', 'Presencial'), ('indicacao', 'Indicação de liderança'), ('outro', 'Outro')], default='instagram', max_length=12, verbose_name='Origem')),
                ('nome_contato', models.CharField(blank=True, max_length=120, verbose_name='Nome de quem trouxe')),
                ('contato', models.CharField(blank=True, max_length=120, verbose_name='Contato (telefone/rede)')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('analise', 'Em análise'), ('respondida', 'Respondida')], default='recebida', max_length=12, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta / encaminhamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrada em')),
            ],
            options={
                'verbose_name': 'Demanda da escuta',
                'verbose_name_plural': 'Demandas da escuta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('municipio', models.CharField(max_length=80, verbose_name='Município')),
                ('funcao', models.CharField(blank=True, help_text='Ex.: presidente de associação, diretor de escola, vereador…', max_length=120, verbose_name='Função / papel')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
                'ordering': ['municipio', 'nome'],
            },
        ),
    ]
