# Generated by Django 5.2.17 on 2026-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornalista', models.CharField(max_length=120, verbose_name='Nome do jornalista')),
                ('veiculo', models.CharField(max_length=120, verbose_name='Veículo de imprensa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail para contato')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='Telefone (opcional)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da matéria')),
                ('texto', models.TextField(verbose_name='Texto da matéria')),
                ('link', models.URLField(blank=True, verbose_name='Link da publicação original (opcional)')),
                ('imagem', models.ImageField(blank=True, upload_to='materias/%Y/%m/', verbose_name='Imagem (opcional)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de revisão'), ('aprovada', 'Aprovada e publicada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=12, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('publicado_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
            ],
            options={
                'verbose_name': 'Matéria enviada',
                'verbose_name_plural': 'Matérias da imprensa',
                'ordering': ['-criado_em'],
            },
        ),
    ]
