# Generated by Django 5.2.17 on 2026-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprensa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('equipe', 'Produzida pela equipe'), ('imprensa', 'Enviada pela imprensa'), ('midia', 'Saiu na mídia')], default='imprensa', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail para contato'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='jornalista',
            field=models.CharField(blank=True, max_length=120, verbose_name='Autor / jornalista'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='veiculo',
            field=models.CharField(max_length=120, verbose_name='Veículo / fonte'),
        ),
    ]
